---
sidebar: sidebar 
permalink: genai-engine-instance.html 
keywords: genai engine, instance, ec2, role, iam role, permissions, security group, inbound, outbound, private endpoints 
summary: 'Quando si implementa l"infrastruttura GenAI, workload Factory crea un"istanza EC2 per il motore GenAI. Crea inoltre un ruolo IAM, un gruppo di protezione e endpoint privati per questa istanza. Potresti voler conoscere più dettagli su questi componenti creati da workload Factory nel tuo ambiente AWS.' 
---
= Componenti per il motore NetApp Genai
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Quando si implementa l'infrastruttura GenAI, workload Factory crea un'istanza EC2 per il motore GenAI. Crea inoltre un ruolo IAM, un gruppo di protezione e endpoint privati per questa istanza. Potresti voler conoscere più dettagli su questi componenti creati da workload Factory nel tuo ambiente AWS.

Tipo di istanza di EC2:: m5.large
Ruolo IAM:: L'istanza del motore Genai ha bisogno delle autorizzazioni per inviare blocchi di dati al modello di incorporamento su Amazon Bedrock e per comunicare con il backend del servizio ai di NetApp. Il ruolo IAM include le seguenti autorizzazioni:
+
--
[source, json]
----
"ssm:Describe*",
"ssm:Get*",
"ssm:List*",
"ssm:PutInventory",
"ssm:PutComplianceItems",
"ssm:PutConfigurePackageResult",
"ssm:SendCommand",
"ssm:UpdateAssociationStatus",
"ssm:UpdateInstanceAssociationStatus",
"ssm:UpdateInstanceInformation",
"ssmmessages:*",
"ec2messages:GetMessages"
----
--
Gruppo di sicurezza:: Le regole in uscita sono aperte a tutto il traffico, mentre le regole in entrata sono completamente chiuse.
Endpoint privati:: Se il VPC di destinazione non ne dispone già, workload Factory crea endpoint privati per l'istanza GenAI Engine EC2 in modo che possa comunicare con i seguenti servizi AWS:
+
--
* Amazon Bedrock
* Amazon EC2
* Amazon Elastic Container Registry (ECR)
* Amazon S3
* AWS Systems Manager (SSM)
* Amazon FSX per NetApp ONTAP
* Amazon CloudWatch


--

