---
settings:
  name: GenAI
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documenti Genai
    url: "/index.html"
  - title: Note di rilascio
    entries:
    - title: Novità
      url: "/whats-new.html"
  - title: Scopri la BlueXP  workload Factory per Genai
    entries:
    - title: Scopri la BlueXP  workload Factory per Genai
      url: "/general/ai-workloads-overview.html"
    - title: Componenti del motore NetApp Genai
      url: "/general/genai-engine-instance.html"
  - title: Utilizza GenAI per creare knowledge base per Amazon Bedrock
    entries:
    - title: Inizia subito
      entries:
      - title: Avvio rapido
        url: "/knowledge-base/quick-start-knowledge-base.html"
      - title: Requisiti della Knowledge base
        url: "/knowledge-base/requirements-knowledge-base.html"
      - title: Identificare le origini dati da aggiungere a una knowledge base
        url: "/knowledge-base/identify-data-sources-knowledge-base.html"
      - title: Implementare l'infrastruttura GenAI
        url: "/knowledge-base/deploy-infrastructure.html"
    - title: Creare una knowledge base
      url: "/knowledge-base/create-knowledgebase.html"
    - title: Testare una base di conoscenza
      url: "/knowledge-base/test-knowledgebase.html"
    - title: Attivare l'autenticazione
      url: "/knowledge-base/activate-authentication.html"
    - title: Pubblicare una knowledge base
      url: "/knowledge-base/publish-knowledgebase.html"
    - title: Utilizzare l'applicazione chatbot di esempio esterna
      url: "/knowledge-base/example-chatbot-application.html"
    - title: Crea un'applicazione ai basata su RAG
      url: "/knowledge-base/create-application.html"
    - title: Cosa fare in seguito
      url: "/knowledge-base/whats-next.html"
  - title: Utilizzare GenAI per creare connettori per Amazon Q Business
    entries:
    - title: Inizia subito
      entries:
      - title: Avvio rapido
        url: "/connector/quick-start-connector.html"
      - title: Requisiti del connettore
        url: "/connector/requirements-connector.html"
      - title: Identificare le origini dati da aggiungere a un connettore
        url: "/connector/identify-data-sources-connector.html"
      - title: Implementare l'infrastruttura GenAI
        url: "/connector/deploy-infrastructure.html"
    - title: Creare un connettore NetApp ONTAP per Amazon Q
      url: "/connector/define-connector.html"
  - title: Amministrare e monitorare
    entries:
    - title: Gestire l'infrastruttura GenAI
      url: "/general/manage-infrastructure.html"
    - title: Gestire le knowledge base
      url: "/knowledge-base/manage-knowledgebase.html"
    - title: Gestire i connettori
      url: "/connector/manage-connector.html"
    - title: Gestire le origini dati
      url: "/general/manage-data-source.html"
    - title: Monitoraggio delle operazioni con Tracker
      url: "/general/monitor-operations.html"
  - title: Conoscenza e supporto
    entries:
    - title: Registrati per ricevere assistenza
      url: "/support-registration.html"
    - title: Risoluzione dei problemi
      url: "/general/troubleshooting.html"
    - title: Richiedi assistenza
      url: "/get-help.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: BlueXP workload factory
  repo: workload-family
