---
sidebar: sidebar 
permalink: knowledge-base/requirements-knowledge-base.html 
keywords: ai, chatbot, prerequisites, bedrock, fsx for ontap, prerequisites, requirements 
summary: 'Verifica che la workload Factory e AWS siano configurati correttamente prima di costruire la tua knowledge base. Ciò include la disponibilità delle credenziali di accesso ad AWS, un file system FSX per ONTAP distribuito che contiene le origini dei dati da integrare nella tua knowledge base, l"accesso al servizio ai Amazon Bedrock e altro ancora.' 
---
= Requisiti della Knowledge base Genai
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verifica che la workload Factory e AWS siano configurati correttamente prima di costruire la tua knowledge base. Ciò include la disponibilità delle credenziali di accesso ad AWS, un file system FSX per ONTAP distribuito che contiene le origini dei dati da integrare nella tua knowledge base, l'accesso al servizio ai Amazon Bedrock e altro ancora.



== Requisiti di base di GenAI

Genai ha requisiti generali che il tuo ambiente deve soddisfare prima di iniziare.

Account e login di fabbrica del carico di lavoro:: Sarà necessario https://docs.netapp.com/us-en/workload-setup-admin/sign-up-saas.html["configurare un account con workload factory"^] ed effettuare l'accesso utilizzando uno dei https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^] .
Credenziali e autorizzazioni AWS:: Devi aggiungere le credenziali AWS alla fabbrica del carico di lavoro con permessi di lettura/scrittura, il che significa che utilizzerai la fabbrica del carico di lavoro in modalità _lettura/scrittura_ per Genai.
+
--
Le autorizzazioni per la modalità _Basic_ e la modalità _Read-only_ non sono attualmente supportate.

Quando imposti le tue credenziali, selezionando i permessi come mostrato di seguito avrai accesso completo alla gestione dei file system FSX per ONTAP e alla distribuzione e gestione dell'istanza Genai EC2 e delle altre risorse AWS necessarie per la tua knowledge base e il tuo chatbot.

https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Scopri come aggiungere le credenziali AWS alla fabbrica di carichi di lavoro"^]

--




== Requisiti della Knowledge base Genai

Se si prevede di lavorare con le knowledge base, accertarsi che l'ambiente soddisfi i seguenti requisiti.

Amazon Bedrock:: Amazon Bedrock ti consente di utilizzare modelli di base e offre le funzionalità per creare applicazioni ai generative.
+
--
Prima di iniziare a utilizzare la fabbrica di carichi di lavoro BlueXP  per Genai, è necessario configurare Amazon Bedrock. L'implementazione Genai deve trovarsi in una regione AWS con Amazon Bedrock abilitato.

* https://docs.aws.amazon.com/bedrock/latest/userguide/setting-up.html["Documentazione AWS: Configurare Amazon Bedrock"^]
* https://docs.aws.amazon.com/bedrock/latest/userguide/knowledge-base-supported.html["Documentazione AWS: Regioni e modelli supportati per le Knowledge base di Amazon Bedrock"^]


Genai classifica nuovamente i risultati di ricerca per impostazione predefinita per migliorare la pertinenza dei risultati. Per ottenere i migliori risultati, assicurati che la configurazione del modello di base Amazon Bedrock includa l'accesso a un modello di re-rank, come Cohere Rank o Amazon Rank, se disponibile nella tua regione.

--
Modello di inclusione:: È necessario attivare il modello di integrazione che si intende utilizzare prima di creare la propria knowledge base. Sono supportati i seguenti modelli di inclusione:
+
--
* Titano embedding G1 - testo
* Titan Embedding testo v2
* Incorporazioni multimodali Titan G1
* Incorporare l'inglese
* Incorpora multilingue
+
https://aws.amazon.com/bedrock/titan/["Scopri di più su Amazon Titan"^]



--
Modello di chat:: Devi attivare il modello di chat di base che intendi utilizzare prima di creare la tua knowledge base. Poiché il supporto dei modelli varia in base alla regione di AWS, fare riferimento a https://docs.aws.amazon.com/bedrock/latest/userguide/models-regions.html["La documentazione di AWS"^] per verificare quali modelli è possibile utilizzare nelle regioni in cui si prevede di implementare la propria knowledge base.
+
--
GenAI supporta vari modelli da antropico, Amazon, Mistral ai, Meta, Jamba e Cohere.

Scopri di più su come utilizzare questi modelli in Amazon Bedrock:

* https://aws.amazon.com/bedrock/claude/["Claude di antropic in Amazon Bedrock"^]
* https://docs.aws.amazon.com/nova/latest/userguide/getting-started-console.html["Guida introduttiva ad Amazon Nova nella console Amazon Bedrock"^]
* https://aws.amazon.com/bedrock/mistral/["Modelli Mistral ai"^]
* https://docs.aws.amazon.com/bedrock/latest/userguide/titan-text-models.html["Modelli di testo Amazon Titan"^]
* https://aws.amazon.com/bedrock/llama/["Modelli meta Llama"^]
* https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-jamba.html["Modelli Jamba"^]
* https://aws.amazon.com/bedrock/cohere/["Modelli Cohere Command"^]


--
File system FSX per ONTAP:: Ti serve almeno un file system FSX per ONTAP:
+
--
* Un file system verrà utilizzato (o creato, se non esiste) dal motore NetApp GenAI per memorizzare il database vettoriale utilizzato dalla knowledge base.
+
Questo file system FSX per ONTAP deve usare FlexVol Volumes. I volumi FlexGroup non sono supportati.

* Uno o più file system conterranno le origini dati che verranno integrate nella knowledge base.
+
Un unico file system FSX per ONTAP può essere utilizzato per entrambi questi scopi oppure è possibile utilizzare più file system FSX per ONTAP.

* Dovrai conoscere la regione, il VPC e la subnet di AWS in cui si trova il file system AWS FSX per ONTAP. Il file system deve trovarsi in una regione AWS in cui è abilitato Amazon Bedrock.
* Dovrai prendere in considerazione le coppie tag key/valore che desideri applicare alle risorse AWS che fanno parte di questa implementazione (opzionale).
* È necessario conoscere le informazioni sulla coppia di chiavi che consentono di connettersi in modo sicuro all'istanza del motore NetApp ai.


https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["Scopri come implementare e gestire i file system FSX per ONTAP"^]

--

